# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import movie_pb2 as proto_dot_movie__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/movie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """The service for movie embedding operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovieEmbedding = channel.unary_unary(
                '/movie.EmbeddingService/GetMovieEmbedding',
                request_serializer=proto_dot_movie__pb2.MovieRequest.SerializeToString,
                response_deserializer=proto_dot_movie__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.AddMovieEmbedding = channel.unary_unary(
                '/movie.EmbeddingService/AddMovieEmbedding',
                request_serializer=proto_dot_movie__pb2.AddMovieRequest.SerializeToString,
                response_deserializer=proto_dot_movie__pb2.AddMovieResponse.FromString,
                _registered_method=True)
        self.GetSimilarMovie = channel.unary_unary(
                '/movie.EmbeddingService/GetSimilarMovie',
                request_serializer=proto_dot_movie__pb2.SimilarMovieRequest.SerializeToString,
                response_deserializer=proto_dot_movie__pb2.SimilarMovieResponse.FromString,
                _registered_method=True)
        self.GetSimilarMovies = channel.unary_unary(
                '/movie.EmbeddingService/GetSimilarMovies',
                request_serializer=proto_dot_movie__pb2.SimilarMoviesRequest.SerializeToString,
                response_deserializer=proto_dot_movie__pb2.SimilarMoviesResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """The service for movie embedding operations.
    """

    def GetMovieEmbedding(self, request, context):
        """Generates an embedding and adds it to the vector database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMovieEmbedding(self, request, context):
        """Adds a movie embedding to the vector database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimilarMovie(self, request, context):
        """Returns the most similar movie given a movie ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimilarMovies(self, request, context):
        """Returns multiple similar movies (e.g., top 5).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovieEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovieEmbedding,
                    request_deserializer=proto_dot_movie__pb2.MovieRequest.FromString,
                    response_serializer=proto_dot_movie__pb2.EmbeddingResponse.SerializeToString,
            ),
            'AddMovieEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMovieEmbedding,
                    request_deserializer=proto_dot_movie__pb2.AddMovieRequest.FromString,
                    response_serializer=proto_dot_movie__pb2.AddMovieResponse.SerializeToString,
            ),
            'GetSimilarMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarMovie,
                    request_deserializer=proto_dot_movie__pb2.SimilarMovieRequest.FromString,
                    response_serializer=proto_dot_movie__pb2.SimilarMovieResponse.SerializeToString,
            ),
            'GetSimilarMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarMovies,
                    request_deserializer=proto_dot_movie__pb2.SimilarMoviesRequest.FromString,
                    response_serializer=proto_dot_movie__pb2.SimilarMoviesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movie.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movie.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """The service for movie embedding operations.
    """

    @staticmethod
    def GetMovieEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.EmbeddingService/GetMovieEmbedding',
            proto_dot_movie__pb2.MovieRequest.SerializeToString,
            proto_dot_movie__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMovieEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.EmbeddingService/AddMovieEmbedding',
            proto_dot_movie__pb2.AddMovieRequest.SerializeToString,
            proto_dot_movie__pb2.AddMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimilarMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.EmbeddingService/GetSimilarMovie',
            proto_dot_movie__pb2.SimilarMovieRequest.SerializeToString,
            proto_dot_movie__pb2.SimilarMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimilarMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.EmbeddingService/GetSimilarMovies',
            proto_dot_movie__pb2.SimilarMoviesRequest.SerializeToString,
            proto_dot_movie__pb2.SimilarMoviesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
